# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/archit/ros rect"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/archit/ros rect"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/archit/ros rect/CMakeFiles" "/home/archit/ros rect/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/archit/ros rect/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named oclimgutil_cl.h_generated

# Build rule for target.
oclimgutil_cl.h_generated: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 oclimgutil_cl.h_generated
.PHONY : oclimgutil_cl.h_generated

# fast build rule for target.
oclimgutil_cl.h_generated/fast:
	$(MAKE) -f CMakeFiles/oclimgutil_cl.h_generated.dir/build.make CMakeFiles/oclimgutil_cl.h_generated.dir/build
.PHONY : oclimgutil_cl.h_generated/fast

#=============================================================================
# Target rules for targets named oclpolyline_cl.h_generated

# Build rule for target.
oclpolyline_cl.h_generated: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 oclpolyline_cl.h_generated
.PHONY : oclpolyline_cl.h_generated

# fast build rule for target.
oclpolyline_cl.h_generated/fast:
	$(MAKE) -f CMakeFiles/oclpolyline_cl.h_generated.dir/build.make CMakeFiles/oclpolyline_cl.h_generated.dir/build
.PHONY : oclpolyline_cl.h_generated/fast

#=============================================================================
# Target rules for targets named oclrect_cl.h_generated

# Build rule for target.
oclrect_cl.h_generated: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 oclrect_cl.h_generated
.PHONY : oclrect_cl.h_generated

# fast build rule for target.
oclrect_cl.h_generated/fast:
	$(MAKE) -f CMakeFiles/oclrect_cl.h_generated.dir/build.make CMakeFiles/oclrect_cl.h_generated.dir/build
.PHONY : oclrect_cl.h_generated/fast

#=============================================================================
# Target rules for targets named cltoheader

# Build rule for target.
cltoheader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cltoheader
.PHONY : cltoheader

# fast build rule for target.
cltoheader/fast:
	$(MAKE) -f CMakeFiles/cltoheader.dir/build.make CMakeFiles/cltoheader.dir/build
.PHONY : cltoheader/fast

#=============================================================================
# Target rules for targets named oclrect_obj

# Build rule for target.
oclrect_obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 oclrect_obj
.PHONY : oclrect_obj

# fast build rule for target.
oclrect_obj/fast:
	$(MAKE) -f CMakeFiles/oclrect_obj.dir/build.make CMakeFiles/oclrect_obj.dir/build
.PHONY : oclrect_obj/fast

#=============================================================================
# Target rules for targets named helper_obj

# Build rule for target.
helper_obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 helper_obj
.PHONY : helper_obj

# fast build rule for target.
helper_obj/fast:
	$(MAKE) -f CMakeFiles/helper_obj.dir/build.make CMakeFiles/helper_obj.dir/build
.PHONY : helper_obj/fast

#=============================================================================
# Target rules for targets named oclpolyline_obj

# Build rule for target.
oclpolyline_obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 oclpolyline_obj
.PHONY : oclpolyline_obj

# fast build rule for target.
oclpolyline_obj/fast:
	$(MAKE) -f CMakeFiles/oclpolyline_obj.dir/build.make CMakeFiles/oclpolyline_obj.dir/build
.PHONY : oclpolyline_obj/fast

#=============================================================================
# Target rules for targets named oclimgutil_obj

# Build rule for target.
oclimgutil_obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 oclimgutil_obj
.PHONY : oclimgutil_obj

# fast build rule for target.
oclimgutil_obj/fast:
	$(MAKE) -f CMakeFiles/oclimgutil_obj.dir/build.make CMakeFiles/oclimgutil_obj.dir/build
.PHONY : oclimgutil_obj/fast

#=============================================================================
# Target rules for targets named vidrect

# Build rule for target.
vidrect: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vidrect
.PHONY : vidrect

# fast build rule for target.
vidrect/fast:
	$(MAKE) -f CMakeFiles/vidrect.dir/build.make CMakeFiles/vidrect.dir/build
.PHONY : vidrect/fast

cltoheader.o: cltoheader.c.o

.PHONY : cltoheader.o

# target to build an object file
cltoheader.c.o:
	$(MAKE) -f CMakeFiles/cltoheader.dir/build.make CMakeFiles/cltoheader.dir/cltoheader.c.o
.PHONY : cltoheader.c.o

cltoheader.i: cltoheader.c.i

.PHONY : cltoheader.i

# target to preprocess a source file
cltoheader.c.i:
	$(MAKE) -f CMakeFiles/cltoheader.dir/build.make CMakeFiles/cltoheader.dir/cltoheader.c.i
.PHONY : cltoheader.c.i

cltoheader.s: cltoheader.c.s

.PHONY : cltoheader.s

# target to generate assembly for a file
cltoheader.c.s:
	$(MAKE) -f CMakeFiles/cltoheader.dir/build.make CMakeFiles/cltoheader.dir/cltoheader.c.s
.PHONY : cltoheader.c.s

helper.o: helper.c.o

.PHONY : helper.o

# target to build an object file
helper.c.o:
	$(MAKE) -f CMakeFiles/helper_obj.dir/build.make CMakeFiles/helper_obj.dir/helper.c.o
.PHONY : helper.c.o

helper.i: helper.c.i

.PHONY : helper.i

# target to preprocess a source file
helper.c.i:
	$(MAKE) -f CMakeFiles/helper_obj.dir/build.make CMakeFiles/helper_obj.dir/helper.c.i
.PHONY : helper.c.i

helper.s: helper.c.s

.PHONY : helper.s

# target to generate assembly for a file
helper.c.s:
	$(MAKE) -f CMakeFiles/helper_obj.dir/build.make CMakeFiles/helper_obj.dir/helper.c.s
.PHONY : helper.c.s

oclhelper.o: oclhelper.c.o

.PHONY : oclhelper.o

# target to build an object file
oclhelper.c.o:
	$(MAKE) -f CMakeFiles/helper_obj.dir/build.make CMakeFiles/helper_obj.dir/oclhelper.c.o
.PHONY : oclhelper.c.o

oclhelper.i: oclhelper.c.i

.PHONY : oclhelper.i

# target to preprocess a source file
oclhelper.c.i:
	$(MAKE) -f CMakeFiles/helper_obj.dir/build.make CMakeFiles/helper_obj.dir/oclhelper.c.i
.PHONY : oclhelper.c.i

oclhelper.s: oclhelper.c.s

.PHONY : oclhelper.s

# target to generate assembly for a file
oclhelper.c.s:
	$(MAKE) -f CMakeFiles/helper_obj.dir/build.make CMakeFiles/helper_obj.dir/oclhelper.c.s
.PHONY : oclhelper.c.s

oclimgutil.o: oclimgutil.c.o

.PHONY : oclimgutil.o

# target to build an object file
oclimgutil.c.o:
	$(MAKE) -f CMakeFiles/oclimgutil_obj.dir/build.make CMakeFiles/oclimgutil_obj.dir/oclimgutil.c.o
.PHONY : oclimgutil.c.o

oclimgutil.i: oclimgutil.c.i

.PHONY : oclimgutil.i

# target to preprocess a source file
oclimgutil.c.i:
	$(MAKE) -f CMakeFiles/oclimgutil_obj.dir/build.make CMakeFiles/oclimgutil_obj.dir/oclimgutil.c.i
.PHONY : oclimgutil.c.i

oclimgutil.s: oclimgutil.c.s

.PHONY : oclimgutil.s

# target to generate assembly for a file
oclimgutil.c.s:
	$(MAKE) -f CMakeFiles/oclimgutil_obj.dir/build.make CMakeFiles/oclimgutil_obj.dir/oclimgutil.c.s
.PHONY : oclimgutil.c.s

oclpolyline.o: oclpolyline.c.o

.PHONY : oclpolyline.o

# target to build an object file
oclpolyline.c.o:
	$(MAKE) -f CMakeFiles/oclpolyline_obj.dir/build.make CMakeFiles/oclpolyline_obj.dir/oclpolyline.c.o
.PHONY : oclpolyline.c.o

oclpolyline.i: oclpolyline.c.i

.PHONY : oclpolyline.i

# target to preprocess a source file
oclpolyline.c.i:
	$(MAKE) -f CMakeFiles/oclpolyline_obj.dir/build.make CMakeFiles/oclpolyline_obj.dir/oclpolyline.c.i
.PHONY : oclpolyline.c.i

oclpolyline.s: oclpolyline.c.s

.PHONY : oclpolyline.s

# target to generate assembly for a file
oclpolyline.c.s:
	$(MAKE) -f CMakeFiles/oclpolyline_obj.dir/build.make CMakeFiles/oclpolyline_obj.dir/oclpolyline.c.s
.PHONY : oclpolyline.c.s

oclrect.o: oclrect.c.o

.PHONY : oclrect.o

# target to build an object file
oclrect.c.o:
	$(MAKE) -f CMakeFiles/oclrect_obj.dir/build.make CMakeFiles/oclrect_obj.dir/oclrect.c.o
.PHONY : oclrect.c.o

oclrect.i: oclrect.c.i

.PHONY : oclrect.i

# target to preprocess a source file
oclrect.c.i:
	$(MAKE) -f CMakeFiles/oclrect_obj.dir/build.make CMakeFiles/oclrect_obj.dir/oclrect.c.i
.PHONY : oclrect.c.i

oclrect.s: oclrect.c.s

.PHONY : oclrect.s

# target to generate assembly for a file
oclrect.c.s:
	$(MAKE) -f CMakeFiles/oclrect_obj.dir/build.make CMakeFiles/oclrect_obj.dir/oclrect.c.s
.PHONY : oclrect.c.s

vidrect.o: vidrect.cpp.o

.PHONY : vidrect.o

# target to build an object file
vidrect.cpp.o:
	$(MAKE) -f CMakeFiles/vidrect.dir/build.make CMakeFiles/vidrect.dir/vidrect.cpp.o
.PHONY : vidrect.cpp.o

vidrect.i: vidrect.cpp.i

.PHONY : vidrect.i

# target to preprocess a source file
vidrect.cpp.i:
	$(MAKE) -f CMakeFiles/vidrect.dir/build.make CMakeFiles/vidrect.dir/vidrect.cpp.i
.PHONY : vidrect.cpp.i

vidrect.s: vidrect.cpp.s

.PHONY : vidrect.s

# target to generate assembly for a file
vidrect.cpp.s:
	$(MAKE) -f CMakeFiles/vidrect.dir/build.make CMakeFiles/vidrect.dir/vidrect.cpp.s
.PHONY : vidrect.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... oclimgutil_cl.h_generated"
	@echo "... oclpolyline_cl.h_generated"
	@echo "... edit_cache"
	@echo "... oclrect_cl.h_generated"
	@echo "... cltoheader"
	@echo "... oclrect_obj"
	@echo "... helper_obj"
	@echo "... oclpolyline_obj"
	@echo "... oclimgutil_obj"
	@echo "... vidrect"
	@echo "... cltoheader.o"
	@echo "... cltoheader.i"
	@echo "... cltoheader.s"
	@echo "... helper.o"
	@echo "... helper.i"
	@echo "... helper.s"
	@echo "... oclhelper.o"
	@echo "... oclhelper.i"
	@echo "... oclhelper.s"
	@echo "... oclimgutil.o"
	@echo "... oclimgutil.i"
	@echo "... oclimgutil.s"
	@echo "... oclpolyline.o"
	@echo "... oclpolyline.i"
	@echo "... oclpolyline.s"
	@echo "... oclrect.o"
	@echo "... oclrect.i"
	@echo "... oclrect.s"
	@echo "... vidrect.o"
	@echo "... vidrect.i"
	@echo "... vidrect.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

